eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod-uri

  application:
    name: api-gateway

  codec:
    max-in-memory-size: 20MB

  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'https://server.aws-esk.com'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true

      routes:
        - id: member-direct
          predicates:
            - Path=/member/**
          filters:
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://member-service.soldesk.svc.cluster.local

        - id: ordering-direct
          predicates:
            - Path=/ordering/**
          filters:
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://ordering-service.soldesk.svc.cluster.local

        - id: product-direct
          predicates:
            - Path=/product/**
          filters:
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://product-service.soldesk.svc.cluster.local

        - id: frontend-direct
          predicates:
            - Path=/frontend/**
          filters:
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://frontend-service.soldesk.svc.cluster.local

        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://member-service.soldesk.svc.cluster.local

        - id: ordering-service
          predicates:
            - Path=/ordering-service/**
          filters:
            - StripPrefix=1
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://ordering-service.soldesk.svc.cluster.local

        - id: product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://product-service.soldesk.svc.cluster.local

        - id: frontend-service
          predicates:
            - Path=/frontend-service/**
          filters:
            - StripPrefix=1
            - name: RequestSize
              args:
                maxSize: 20MB
          uri: http://frontend-service.soldesk.svc.cluster.local

jwt:
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5